# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a3297b05be3f188568151b89190210f783177e1d2be7ce2e0c0621797b8559c20bf07490192a3accb9b35559ad8703fd43fff8a2273737d75febd47988e4d471

test:
  secret_key_base: 945556c26362a41769a5f8ce7725cc6e36251fb64fec1a52cbf2ae4742eae59a3f20be4e6065e6dd1ff47b5863f32196275989309a81e76181fd1730f92bc0c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
